//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ConsoleApp1.ListOfDealBase {

    public partial class WeekRecords : XPLiteObject {
        int fId;
        [Key(true)]
        public int Id {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Actions fActionId;
        [Association(@"WeekRecordsReferencesActions")]
        public Actions ActionId {
            get { return fActionId; }
            set { SetPropertyValue<Actions>(nameof(ActionId), ref fActionId, value); }
        }
        DateTime fDateAdd;
        public DateTime DateAdd {
            get { return fDateAdd; }
            set { SetPropertyValue<DateTime>(nameof(DateAdd), ref fDateAdd, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        string fWeekId;
        [Size(50)]
        public string WeekId {
            get { return fWeekId; }
            set { SetPropertyValue<string>(nameof(WeekId), ref fWeekId, value); }
        }
        bool fIsCompletedInWeek;
        public bool IsCompletedInWeek {
            get { return fIsCompletedInWeek; }
            set { SetPropertyValue<bool>(nameof(IsCompletedInWeek), ref fIsCompletedInWeek, value); }
        }
    }

}
